# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# получение информации по датчику
GET {{baseUrl}}/sensors/2/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensor/
Content-Type: application/json

###

# обновление датчика
PATCH {{baseUrl}}/sensor/1/
Content-Type: application/json

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

