# Generated by Django 5.1.7 on 2025-04-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('author', models.CharField(max_length=64, verbose_name='Автор')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Обложка')),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
                ('slug', models.SlugField(allow_unicode=True, null=True, verbose_name='slug')),
            ],
        ),
    ]
