# Generated by Django 5.1.7 on 2025-04-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.URLField()),
                ('release_date', models.CharField(max_length=10)),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
        ),
    ]
