# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Виноград",
  "description": "Крупный и оочень сладкий!"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/8/
Content-Type: application/json

{
  "title": "Виноград",
  "description": "Крупный, сладкий, без косточек"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/2/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?src=жёл
Content-Type: application/json

###

# создание склада
POST  {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "В подвале пятого дома",
  "positions": [
    {
      "product": 5,
      "price": 80,
      "quantity": 150
    },
    {
      "product": 8,
      "price": 320,
      "quantity": 100
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/2/
Content-Type: application/json

{
  "positions": [
    {
      "product": 5,
      "price": 75,
      "quantity": 200
    },
    {
      "product": 7,
      "price": 250,
      "quantity": 100
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=5
Content-Type: application/json

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?src=Помид
Content-Type: application/json

###

# Упорядочивание выбранных продуктов по названию
GET {{baseUrl}}/products/?src=жёл&ord=title
Content-Type: application/json
